apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-demo
  namespace: tododemo
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: bb-site
        image: docker.io/johngatdocker2022/todoapp:v2
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: bb-entrypoint
  namespace: tododemo
spec:
  type: LoadBalancer
  selector:
    bb: web
  ports:
  - port: 80
    targetPort: 3000
